let songs = [
  {
    id: 1,
    name: "sajni",
    artist: "arijit singh",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "romantic",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
  {
    id: 2,
    name: "moh moh ke",
    artist: "arijit singh",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "romantic",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
  {
    id: 3,
    name: "moh moh ke",
    artist: "arijit singh",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "romantic",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
  {
    id: 4,
    name: "moh moh ke",
    artist: "khan",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "qawwali",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
  {
    id: 5,
    name: "moh moh ke",
    artist: "khan",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "qawwali",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
  {
    id: 6,
    name: "sajni",
    artist: "khan",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "qawwali",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
  {
    id: 7,
    name: "sajni",
    artist: "khan",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "pop",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
  {
    id: 8,
    name: "sajni",
    artist: "jackson",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "pop",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
  {
    id: 9,
    name: "sajni",
    artist: "jackson",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "pop",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
  {
    id: 10,
    name: "moh moh ke",
    artist: "jackson",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "ghazal",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
  {
    id: 11,
    name: "moh moh ke",
    artist: "sonu nigam",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "ghazal",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
  {
    id: 12,
    name: "moh moh ke",
    artist: "sonu nigam",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "ghazal",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
  {
    id: 13,
    name: "moh moh ke",
    artist: "sonu nigam",
    img: "../music-player/assets/audio-img/sajni-arijit.jpg",
    genre: "ghazal",
    source: "../music-player/assets/audio/sajni-arijit.mp3",
  },
];

let playlist = [
  {
    coding: [2, 3, 4],
    travel: [1, 5, 6],
  },
];

export { songs, playlist };
